ansible_user: "VoughtNet\\svc-ansible"
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_port: 5985
ansible_winrm_server_cert_validation: ignore

eval_stig_source: "\\\\192.168.10.198\\Evaluate-STIG\\Evaluate-STIG_1.2507.5"

# âœ… This must end at the version folder, not the subfolder
eval_stig_dest: "C:\\ProgramData\\Evaluate-STIG_1.2507.5"

results_share_root: "\\\\192.168.10.198\\stig-results"
