# Where all STIG CKLs and role folders live
stig_share_root: '\\192.168.10.198\STIG-Results'

# STIG roles we want to roll up
stig_roles:
  - domain_controllers
  - member_servers
  - workstations

# (Reserved for future master dashboard script)
stig_master_report_path: '\\192.168.10.198\STIG-Results\Reports'

# PowerShell command used on the controller:
powershell_path: 'pwsh'
