---
# V-205730 â€” TLS 1.2 must be enabled

- name: Enable TLS 1.2 Server
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
    name: Enabled
    data: 1
    type: dword

- name: Enable TLS 1.2 Client
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
    name: Enabled
    data: 1
    type: dword

