---
- name: Test SMB Access from WinRM Host
  hosts: domain_controllers
  gather_facts: false

  vars:
    share_root_unc: "\\\\192.168.10.198\\STIG-Results"

  tasks:
    - name: Test UNC path
      ansible.windows.win_powershell:
        script: |
          Test-Path "{{ share_root_unc }}"
