---
- name: Update Evaluate-STIG on all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Remove old Evaluate-STIG
      ansible.windows.win_file:
        path: "{{ eval_stig_dest }}"
        state: absent

    - name: Run copy role to deploy new version
      include_role:
        name: stig-copy
