---
- name: Unblock Evaluate-STIG Files if Execution Fails
  hosts: all
  gather_facts: no

  vars:
    stig_local_path: "C:\\ProgramData\\Evaluate-STIG_1.2507.5"

  tasks:
    - name: Unblock all files in Evaluate-STIG directory
      ansible.windows.win_powershell:
        script: |
          Get-ChildItem "{{ stig_local_path }}" -Recurse | Unblock-File -ErrorAction SilentlyContinue
